import { SceneData } from "./scene/SceneManager";

export const data: SceneData = {
  username: "@testuser",
  avatarUrl: "/images/profile_picture.jpeg",
  contributionsCount: 1390,
  commitsCount: 1260,
  pullRequestsCount: 116,
  openedIssuesCount: 0,
  mostProductiveDay: "Monday",
  mostProductiveHour: "12AM",
  repositoriesCreatedCount: 14,
  starsReceivedCount: 0,
  mostUsedLanguages: [
    "MDX",
    "Makefile",
    "GLSL",
    "Shell",
    "Go",
    "SCSS",
    "Dockerfile",
    "HTML",
    "CSS",
    "TypeScript",
    "JavaScript",
  ],
  starredRepositories: [
    "wdc-saas-starter-kit",
    "yazi",
    "Pearcleaner",
    "video-rendering-server",
    "react-video-editor",
    "node",
    "vitepress",
    "solid-ui",
    "vim-be-good",
    "awesome-selfhosted",
  ],
};
